---
title: "Chart colours"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chart colours}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(nisracolours)
library(ggplot2)

theme_set(theme_minimal(base_size = 12))
```

The official NISRA colours (shown on the left in the charts below) are limited in number and can cause accessibility problems in charts.

```{r colours, fig.show="hold", out.width="45%", fig.height=3, fig.alt="Two bar charts side-by-side using the official NISRA colours on the left and the NISRA colour palette on the right"}
df <- data.frame(
  group = c("Employed", "Unemployed", "Inactive"),
  rate = c(0.716, 0.423, 0.272)
)

ggplot(df, aes(group, rate, fill = group)) +
  geom_col() +
  scale_fill_manual(values = old_colours) +
  guides(fill = guide_none(), x = guide_none(), y = guide_none()) +
  labs(x = NULL, y = NULL)


ggplot(df, aes(group, rate, fill = group)) +
  geom_col() +
  scale_fill_discrete_nisra() +
  guides(fill = guide_none(), x = guide_none(), y = guide_none()) +
  labs(x = NULL, y = NULL)
```
